sets.weaponskill = {
	element = {
		Transfixion={
			Fire = {neck="Light Gorget",waist="Light Belt"},
			Earth = {neck="Light Gorget",waist="Light Belt"},
			Water = {neck="Light Gorget",waist="Light Belt"},
			Wind = {neck="Light Gorget",waist="Light Belt"},
			Ice = {neck="Light Gorget",waist="Light Belt"},
			Lightning = {neck="Light Gorget",waist="Light Belt"},
			Light = {neck="Light Gorget",waist="Light Belt"},
			Dark = {neck="Light Gorget",waist="Light Belt"},
			},
		Compression={
			Fire = {neck="Shadow Gorget",waist="Shadow Belt"},
			Earth = {neck="Shadow Gorget",waist="Shadow Belt"},
			Water = {neck="Shadow Gorget",waist="Shadow Belt"},
			Wind = {neck="Shadow Gorget",waist="Shadow Belt"},
			Ice = {neck="Shadow Gorget",waist="Shadow Belt"},
			Lightning = {neck="Shadow Gorget",waist="Shadow Belt"},
			Light = {neck="Shadow Gorget",waist="Shadow Belt"},
			Dark = {neck="Shadow Gorget",waist="Shadow Belt"},
			},
		Liquefaction={
			Fire = {neck="Flame Gorget",waist="Flame Belt"},
			Earth = {neck="Flame Gorget",waist="Flame Belt"},
			Water = {neck="Flame Gorget",waist="Flame Belt"},
			Wind = {neck="Flame Gorget",waist="Flame Belt"},
			Ice = {neck="Flame Gorget",waist="Flame Belt"},
			Lightning = {neck="Flame Gorget",waist="Flame Belt"},
			Light = {neck="Flame Gorget",waist="Flame Belt"},
			Dark = {neck="Flame Gorget",waist="Flame Belt"},
			},
		Scission={
			Fire = {neck="Soil Gorget",waist="Soil Belt"},
			Earth = {neck="Soil Gorget",waist="Soil Belt"},
			Water = {neck="Soil Gorget",waist="Soil Belt"},
			Wind = {neck="Soil Gorget",waist="Soil Belt"},
			Ice = {neck="Soil Gorget",waist="Soil Belt"},
			Lightning = {neck="Soil Gorget",waist="Soil Belt"},
			Light = {neck="Soil Gorget",waist="Soil Belt"},
			Dark = {neck="Soil Gorget",waist="Soil Belt"},
			},
		Reverberation={
			Fire = {neck="Aqua Gorget",waist="Aqua Belt"},
			Earth = {neck="Aqua Gorget",waist="Aqua Belt"},
			Water = {neck="Aqua Gorget",waist="Aqua Belt"},
			Wind = {neck="Aqua Gorget",waist="Aqua Belt"},
			Ice = {neck="Aqua Gorget",waist="Aqua Belt"},
			Lightning = {neck="Aqua Gorget",waist="Aqua Belt"},
			Light = {neck="Aqua Gorget",waist="Aqua Belt"},
			Dark = {neck="Aqua Gorget",waist="Aqua Belt"},
			},
		Detonation={
			Fire = {neck="Breeze Gorget",waist="Breeze Belt"},
			Earth = {neck="Breeze Gorget",waist="Breeze Belt"},
			Water = {neck="Breeze Gorget",waist="Breeze Belt"},
			Wind = {neck="Breeze Gorget",waist="Breeze Belt"},
			Ice = {neck="Breeze Gorget",waist="Breeze Belt"},
			Lightning = {neck="Breeze Gorget",waist="Breeze Belt"},
			Light = {neck="Breeze Gorget",waist="Breeze Belt"},
			Dark = {neck="Breeze Gorget",waist="Breeze Belt"},
			},
		Induration={
			Fire = {neck="Snow Gorget",waist="Snow Belt"},
			Earth = {neck="Snow Gorget",waist="Snow Belt"},
			Water = {neck="Snow Gorget",waist="Snow Belt"},
			Wind = {neck="Snow Gorget",waist="Snow Belt"},
			Ice = {neck="Snow Gorget",waist="Snow Belt"},
			Lightning = {neck="Snow Gorget",waist="Snow Belt"},
			Light = {neck="Snow Gorget",waist="Snow Belt"},
			Dark = {neck="Snow Gorget",waist="Snow Belt"},
			},
		Impaction={
			Fire = {neck="Thunder Gorget",waist="Thunder Belt"},
			Earth = {neck="Thunder Gorget",waist="Thunder Belt"},
			Water = {neck="Thunder Gorget",waist="Thunder Belt"},
			Wind = {neck="Thunder Gorget",waist="Thunder Belt"},
			Ice = {neck="Thunder Gorget",waist="Thunder Belt"},
			Lightning = {neck="Thunder Gorget",waist="Thunder Belt"},
			Light = {neck="Thunder Gorget",waist="Thunder Belt"},
			Dark = {neck="Thunder Gorget",waist="Thunder Belt"},
			},
		Gravitation={
			Fire = {neck="Shadow Gorget",waist="Shadow Belt"},
			Earth = {neck="Soil Gorget",waist="Soil Belt"},
			Water = {neck="Soil Gorget",waist="Soil Belt"},
			Wind = {neck="Shadow Gorget",waist="Shadow Belt"},
			Ice = {neck="Shadow Gorget",waist="Shadow Belt"},
			Lightning = {neck="Soil Gorget",waist="Soil Belt"},
			Light = {neck="Soil Gorget",waist="Soil Belt"},
			Dark = {neck="Shadow Gorget",waist="Shadow Belt"},
			},
		Distortion={
			Fire = {neck="Aqua Gorget",waist="Aqua Belt"},
			Earth = {neck="Snow Gorget",waist="Snow Belt"},
			Water = {neck="Aqua Gorget",waist="Aqua Belt"},
			Wind = {neck="Aqua Gorget",waist="Aqua Belt"},
			Ice = {neck="Snow Gorget",waist="Snow Belt"},
			Lightning = {neck="Snow Gorget",waist="Snow Belt"},
			Light = {neck="Aqua Gorget",waist="Aqua Belt"},
			Dark = {neck="Snow Gorget",waist="Snow Belt"},
			},
		Fusion={
			Fire = {neck="Flame Gorget",waist="Flame Belt"},
			Earth = {neck="Light Gorget",waist="Light Belt"},
			Water = {neck="Light Gorget",waist="Light Belt"},
			Wind = {neck="Flame Gorget",waist="Flame Belt"},
			Ice = {neck="Flame Gorget",waist="Flame Belt"},
			Lightning = {neck="Light Gorget",waist="Light Belt"},
			Light = {neck="Light Gorget",waist="Light Belt"},
			Dark = {neck="Flame Gorget",waist="Flame Belt"},
			},
		Fragmentation={
			Fire = {neck="Breeze Gorget",waist="Breeze Belt"},
			Earth = {neck="Breeze Gorget",waist="Breeze Belt"},
			Water = {neck="Thunder Gorget",waist="Thunder Belt"},
			Wind = {neck="Breeze Gorget",waist="Breeze Belt"},
			Ice = {neck="Thunder Gorget",waist="Thunder Belt"},
			Lightning = {neck="Thunder Gorget",waist="Thunder Belt"},
			Light = {neck="Thunder Gorget",waist="Thunder Belt"},
			Dark = {neck="Breeze Gorget",waist="Breeze Belt"},
			},
		Light={
			Fire = {neck="Flame Gorget",waist="Flame Belt"},
			Earth = {neck="Breeze Gorget",waist="Breeze Belt"},
			Water = {neck="Thunder Gorget",waist="Thunder Belt"},
			Wind = {neck="Breeze Gorget",waist="Breeze Belt"},
			Ice = {neck="Flame Gorget",waist="Flame Belt"},
			Lightning = {neck="Thunder Gorget",waist="Thunder Belt"},
			Light = {neck="Light Gorget",waist="Light Belt"},
			Dark = {neck="Light Gorget",waist="Light Belt"},
			},
		Darkness={
			Fire = {neck="Aqua Gorget",waist="Aqua Belt"},
			Earth = {neck="Soil Gorget",waist="Soil Belt"},
			Water = {neck="Aqua Gorget",waist="Aqua Belt"},
			Wind = {neck="Snow Gorget",waist="Snow Belt"},
			Ice = {neck="Snow Gorget",waist="Snow Belt"},
			Lightning = {neck="Soil Gorget",waist="Soil Belt"},
			Light = {neck="Shadow Gorget",waist="Shadow Belt"},
			Dark = {neck="Shadow Gorget",waist="Shadow Belt"},
			},
		},
	types = {
		['Hand-to-Hand'] = {head="Tokon Hachimaki"},
		['Dagger'] = {head="Issen Hachimaki"},
		['Sword'] = {head="Kensho Hachimaki"},
		['Great Sword'] = {head="Hako Hachimaki"},
		['Axe'] = {head="Ryoshi Hachimaki"},
		['Great Axe'] = {head="Senshin Hachimaki"},
		['Scythe'] = {head="Rekka Hachimaki"},
		['Polearm'] = {head="Shitotsu Hachimaki"},
		['Katana'] = {head="Kanja Hachimaki"},
		['Great Katana'] = {head="Kengo Hachimaki"},
		['Club'] = {head="Rokugo Hachimaki"},
		['Staff'] = {head="Hakke Hachimaki"},
		['Archery'] = {head="Shunten Hachimaki"},
		['Marksmanship'] = {head="Saika Hachimaki"},
		['Throwing'] = {},
		}
	}

function equip_elemental_ws_Gear(spell, mid)
	local dwelement = world.day_element
	if world.weather_element ~= "None" and world.weather_element ~= nil then
		dwelement = world.weather_element
	end
	if spell.type == "WeaponSkill" and not spell.skillchain_a == nil and not mid then
		equip_pre_cast = set_combine(equip_pre_cast, sets.weaponskill.types[spell.skill])
		equip_pre_cast = set_combine(equip_pre_cast, sets.weaponskill.element[spell.skillchain_a][dwelement])
	elseif spell.type == "WeaponSkill" and not spell.skillchain_a == nil and mid then
		equip_mid_cast = set_combine(equip_pre_cast, sets.weaponskill.types[spell.skill])
		equip_mid_cast = set_combine(equip_pre_cast, sets.weaponskill.element[spell.skillchain_a][dwelement])
	end
end